#!/bin/sh

if test -e "$HOME"/.config/ublue/firstboot-done; then
    echo "Already ran"
    exit 0
fi

(
echo "# Waiting for Internet connection"
until /usr/bin/ping -q -c 1 flathub.org; do sleep 1; done
echo "00"

echo "# Removing Filtered Flathub Repository"
/usr/bin/flatpak remote-delete flathub --force ||:
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Removing Filtered Flathub Repo Failed"
        exit 1
fi
echo "3"

echo "# Enabling Flathub Repository"
/usr/bin/flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Adding Flathub Repo Failed"
        exit 1
fi
echo "5"

echo "# Replacing Fedora Flatpaks with Flathub Ones"
/usr/bin/flatpak install --user --noninteractive org.gnome.Platform//43
/usr/bin/flatpak install --user --noninteractive --reinstall flathub $(flatpak list --app-runtime=org.fedoraproject.Platform --columns=application | tail -n +1 )
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Replacing Fedora Flatpaks Failed"
        exit 1
fi
echo "20"

echo "# Removing Fedora Flatpak Repository"
/usr/bin/flatpak remote-delete fedora --force ||:
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Removing Fedora Flatpak Repo Failed"
        exit 1
fi
echo "25"

echo "# Installing Firefox"
/usr/bin/flatpak install --user --noninteractive flathub org.mozilla.firefox
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing Firefox Failed"
        exit 1
fi
echo "30"

echo "# Installing LibreWolf"
/usr/bin/flatpak install --user --noninteractive flathub io.gitlab.librewolf-community
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing LibreWolf Failed"
        exit 1
fi
echo "40"

echo "# Installing Extension Manager"
/usr/bin/flatpak install --user --noninteractive flathub com.mattjakeman.ExtensionManager
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing Extension Manager Failed"
        exit 1
fi
echo "50"

echo "# Installing LibreOffice"
/usr/bin/flatpak install --user --noninteractive flathub org.libreoffice.LibreOffice
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing LibreOffice Failed"
        exit 1
fi
echo "70"

echo "# Installing KopiaUI Backup"
/usr/bin/flatpak install --user --noninteractive flathub io.kopia.KopiaUI
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing KopiaUI Failed"
        exit 1
fi
echo "80"

echo "# Installing Font Downloader"
/usr/bin/flatpak install --user --noninteractive flathub org.gustavoperedo.FontDownloader
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing FontDownloader Failed"
        exit 1
fi
echo "85"

echo "# Installing Flatseal"
/usr/bin/flatpak install --user --noninteractive flathub com.github.tchx84.Flatseal
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing Flatseal Failed"
        exit 1
fi
echo "90"

echo "# Installing Spotify"
/usr/bin/flatpak install --user --noninteractive flathub com.spotify.Client
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing Spotify Failed"
        exit 1
fi
echo "91"

echo "# Installing Steam"
/usr/bin/flatpak install --user --noninteractive flathub com.valvesoftware.Steam
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing Steam Failed"
        exit 1
fi
echo "92"

echo "# Installing Bitwarden"
/usr/bin/flatpak install --user --noninteractive flathub com.bitwarden.desktop
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing Bitwarden Failed"
        exit 1
fi
echo "93"

echo "# Installing Signal Desktop"
/usr/bin/flatpak install --user --noninteractive flathub org.signal.Signal
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing Signal Desktop Failed"
        exit 1
fi
echo "94"

echo "# Installing Celluloid Media Player"
/usr/bin/flatpak install --user --noninteractive flathub io.github.celluloid_player.Celluloid
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing Celluloid Failed"
        exit 1
fi
echo "100"

echo "# Reticulating Final Splines"
mkdir -p "$HOME"/.config/ublue/
touch "$HOME"/.config/ublue/firstboot-done

) | 
     
   zenity --progress --title="uBlue Desktop Firstboot" --percentage=0 --auto-close --no-cancel --width=300

if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Firstboot Configuration Error"
fi
